HLint commit hook

diff --git a/git_template/hooks/pre-commit b/git_template/hooks/pre-commit
--- a/git_template/hooks/pre-commit
+++ b/git_template/hooks/pre-commit
@@ -1,8 +1,33 @@
 #!/bin/sh
-shell_lint=$(git ls-files "*.sh" | xargs shellcheck)
-if [ "$?" -ne "0" ]; then
-    echo "Shellcheck linting errors:"
-    echo "$shell_lint"
-    exit 1
-fi
-exit 0
+analyze_shell()
+{
+    shell_files=$(git ls-files "*.sh")
+    if [ -z "$shell_files" ]; then
+        return
+    fi
+
+    shell_lint=$(git ls-files "*.sh" | xargs shellcheck)
+    if [ "$?" -ne "0" ]; then
+        echo "Shellcheck linting errors:"
+        echo "$shell_lint"
+        exit 1
+    fi
+}
+
+analyze_haskell()
+{
+    haskell_files=$(git ls-files "*.hs")
+    if [ -z "$haskell_files" ]; then
+        return
+    fi
+
+    haskell_lint=$(git ls-files "*.sh" | xargs shellcheck)
+    if [ "$?" -ne "0" ]; then
+        echo "HLint errors:"
+        echo "$haskell_lint"
+        exit 1
+    fi
+}
+
+analyze_shell
+analyze_haskell
